namespace Systems.AbilitySystemGraph.VM
{
    /// <summary>
    /// Defines the type of action the main thread needs to execute on behalf of the Job.
    /// </summary>
    public enum CommandType
    {
        None = 0,
        ApplyEffect = 1,
        PlayCue = 2
    }

    /// <summary>
    /// A struct generated by the VM and consumed by the main thread.
    /// Pushed to a NativeQueue during Job execution.
    /// </summary>
    public struct AbilityCommand
    {
        public CommandType Type;
        
        // Identity of the asset to use (e.g., index of the Effect ScriptableObject in an array)
        public int AssetId;
        
        // Potential dynamic magnitude calculated by the graph
        public float Magnitude;
    }
}
