using System;
using System.Collections.Generic;
using AbilitySystem.Runtime.Abilities;
using AbilitySystem.Runtime.Core;
using Systems.AbilitySystemGraph.VM;
using UnityEngine;
using Sirenix.OdinInspector;

namespace Systems.AbilitySystemGraph.Runtime
{
    /// <summary>
    /// A single asset that contains both the Ability Configuration, 
    /// the visual logic graph (Editor-only), and the baked bytecode (Runtime).
    /// </summary>
    [CreateAssetMenu(menuName = "Ability System/Graph Ability")]
    public class GraphAbilityDefinition : AbilityDefinition
    {
        [Header("Runtime Bytecode (Generated by Baker)")]
        [ReadOnly, SerializeField]
        public List<Instruction> CompiledInstructions = new List<Instruction>();
        
        [ReadOnly, SerializeField]
        public int FloatRegisterCount;

        /// <summary>
        /// The raw GTK graph data. This is serialized into the ScriptableObject.
        /// It is only used by the Editor and ignored by the Burst VM at runtime.
        /// </summary>
        [HideInInspector, SerializeField]
        public string SerializedGraphData;

        public override Type AbilityType() => typeof(GraphAbility);

        public override Ability ToAbility(IAbilitySystem owner)
        {
            return new GraphAbility(this, owner);
        }
    }
}
