name: Get Activation File 🔑
on: [workflow_dispatch] # Run manually from Actions tab
jobs:
  activation:
    name: Request Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Activation File
        uses: game-ci/unity-request-activation-file@v2
      - name: Upload .alf as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: activation-file
          path: ./*.alf
